### ISSUE TITLE
[TODO] Fix the TopBar/TopNav

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/radio_logger#58]
The TopBar/TopNav is not working.  I extracted this out as a separate issue even though it has been mentioned in a few.

Fix the TopBar/TopNav so that all of the icons work.

This app uses jQuery, FontAwesome, Bootstrap, PopperJS, Google Fonts in the front end loaded as CDN's on each HTML. No other frontend frameworks. (PopperJS also deprecated and changed names.

- [ ] Hamburger should bring out 250px offcanvas drawer that is a side navigation / sidebar
Toggle Icons 

- [ ] Toggle Icon (on and off) should  change state when user clicks on it. It should be coupled to a theme.js which changes the theme to light and darkmode.  Background of light mode is too  bright.

- [ ] User Icon / Avatar needs a dropdown menu (See separate issue on this one)

- [ ] "Radio Logger" text is a link to nowhere. It should route to "/".

- [ ] Notifications Icon (Bell) is just a icon.  Not even a button yet and no red or black or white circle/dot with notification count.

- [ ] No logo.svg // logo.png (choose a radio 

- [ ] Messages Icon is the same.
